### ISSUE TITLE
socket getting disconnected

### ISSUE THREAD

**Issue by ninadjoshi20** [saran-surya/cassata#2]
I have used cassata proxy server for cowin API and deployed in heroku. But every 10 mins the socket gets disconnected and its stops the proxy server. when I tried to use cassata in local the socket would not disconnect unless I refreshed the page or used Terminate Session button. Is there any solution for this?

**Comment by saran-surya** [comment]
Hi @ninadjoshi20 , Are you accessing the proxy client with your mobile phone or computer, Mobile phones are facing some issues, I have checked with my Heroku server, they are working fine. Kindly provide the above details.

**Comment by saran-surya** [comment]
Hi @ninadjoshi20 , currently closing the issue, As planned it is not advised to maintain sessions for prolonged periods on a mobile phone, thus Kindly use it with a computer, The feature is still present in the current version but will be removed in the future versions.

https://github.com/saran-surya/cassata/blob/main/README.md#-depricated-on-mobile

Thankyou for the issue, 
Happy Coding 👍🏻
